var data = [
  {
    id: "1",
    name: "nft-marketplace",
    filter: "web",
    description: "JavaScript/React/React-Native",
    link: "https://lucky-tooth-1581.on.fleek.co/",
    repo: "https://github.com/Derimarg/nft_marketplace_site",
  },
  {
    id: "2",
    name: "code-command",
    filter: "web",
    description: "React/Heroku/MongoDB",
    link: "https://lucky-tooth-1581.on.fleek.co/",
    repo: "https://github.com/Derimarg/nft_marketplace_site",
  },
  {
    id: "3",
    name: "forge-project",
    filter: "web",
    description: "HTML/CSS/JS/Node/Express/MySQL/Handlebars",
    link: "https://forge-team.herokuapp.com/splash",
    repo: "https://github.com/Derimarg/Forge",
  },
  {
    id: "4",
    name: "git-it-done",
    filter: "card",
    description: "HTML/Bootstrap/JavaScript",
    link: "https://derimarg.github.io/git-it-done/",
    repo: "https://github.com/Derimarg/git-it-done",
  },
  {
    id: "5",
    name: "work-day-scheduler",
    filter: "app",
    description: "HTML/CSS/JavaScript",
    link: "https://derimarg.github.io/work-day-scheduler/",
    repo: "https://github.com/Derimarg/work-day-scheduler",
  },
  {
    id: "6",
    name: "run-buddy",
    filter: "web",
    description:
      "Fitness center where recreational and professional athletes can work out.",
    technologies: "HTML/CSS/JS",
    demo: "https://derimarg.github.io/run-buddy/",
    demoDesc: "Live Demo",
    source: "https://github.com/Derimarg/run-buddy",
    sourceDesc: "Source",
  },
  {
    id: "7",
    name: "just-tech-news",
    filter: "card",
    description: "Node/MySQL/Sequalize",
    link: "https://just-tech-news-dapp.herokuapp.com/",
    repo: "https://github.com/Derimarg/just-tech-news",
  },
  {
    id: "8",
    name: "note-taker",
    filter: "app",
    description:
      "Used to write and save notes. This application will use an Express.js back end and will save and retrieve note data from a JSON file.",
    technologies: "Node/Express/Bootstrap/FontAwesome/CSS/JS/HTML",
    demo: "my-notes-taker.herokuapp.com/",
    demoDesc: "Live Demo",
    source: "https://github.com/Derimarg/note-taker",
    sourceDesc: "Source",
  },
  {
    id: "9",
    name: "taskmaster-pro",
    filter: "web",
    description: "To Do app that allows to organized tasks.",
    technologies: "HTML/CSS/JavaScript",
    demo: "https://derimarg.github.io/taskmaster-pro/",
    demoDesc: "Live Demo",
    source: "https://github.com/Derimarg/taskmaster-pro",
    sourceDesc: "Source",
  },

  {
    id: "10",
    name: "weather-dashboard",
    filter: "app",
    description:
      "Allow to search for a city to get the current weather and 5 day forecast. Cities that users previously search will be displayed as history.",
    technologies: "JavaScript/API/Bootstrap",
    demo: "https://derimarg.github.io/weather-dashboard/",
    demoDesc: "Live Demo",
    source: "https://github.com/Derimarg/weather-dashboard",
    sourceDesc: "Source",
  },
  {
    id: "11",
    name: "tech-blog",
    filter: "card",
    description:
      "CMS-style blog site about tech news that publish articles, blog posts, thoughts and opinions.",
    technologies: "Node/MySQL/Sequalize",
    demo: "https://dg-tech-blog.herokuapp.com/",
    demoDesc: "Live Demo",
    source: "https://github.com/Derimarg/tech-blog",
    sourceDesc: "Source",
  },
  {
    id: "12",
    name: "password-generator",
    filter: "app",
    description:
      "This program give you the ability of generate a random secure password based on your needs.",
    technologies: "HTML/CSS/JavaScript",
    demo: "https://derimarg.github.io/password-generator/",
    demoDesc: "Live Demo",
    source: "https://github.com/Derimarg/password-generator",
    sourceDesc: "Source",
  },
];

export default data;
