var data = [
  {
    id: "1",
    name: "nft-marketplace",
    filter: "web",
    description: "JavaScript/React/React-Native",
    link: "https://lucky-tooth-1581.on.fleek.co/",
    repo: "https://github.com/Derimarg/nft_marketplace_site",
  },
  {
    id: "2",
    name: "code-command",
    filter: "web",
    description: "React/Heroku/MongoDB",
    link: "https://lucky-tooth-1581.on.fleek.co/",
    repo: "https://github.com/Derimarg/nft_marketplace_site",
  },
  {
    id: "3",
    name: "forge-project",
    filter: "web",
    description: "HTML/CSS/JS/Node/Express/MySQL/Handlebars",
    link: "https://forge-team.herokuapp.com/splash",
    repo: "https://github.com/Derimarg/Forge",
  },
  {
    id: "4",
    name: "git-it-done",
    filter: "card",
    description: "HTML/Bootstrap/JavaScript",
    link: "https://derimarg.github.io/git-it-done/",
    repo: "https://github.com/Derimarg/git-it-done",
  },
  {
    id: "5",
    name: "work-day-scheduler",
    filter: "app",
    description: "HTML/CSS/JavaScript",
    link: "https://derimarg.github.io/work-day-scheduler/",
    repo: "https://github.com/Derimarg/work-day-scheduler",
  },
  {
    id: "6",
    name: "run-buddy",
    filter: "web",
    description: "HTML/CSS",
    link: "https://derimarg.github.io/run-buddy/",
    repo: "https://github.com/Derimarg/run-buddy",
  },
  {
    id: "7",
    name: "just-tech-news",
    filter: "card",
    description: "Node/MySQL/Sequalize",
    link: "https://just-tech-news-dapp.herokuapp.com/",
    repo: "https://github.com/Derimarg/just-tech-news",
  },
  {
    id: "8",
    name: "note-taker",
    filter: "app",
    description: "Node/Express/Bootstrap",
    link: "my-notes-taker.herokuapp.com/",
    repo: "https://github.com/Derimarg/note-taker",
  },
  {
    id: "9",
    name: "taskmaster-pro",
    filter: "web",
    description: "HTML/CSS/JavaScript",
    link: "https://derimarg.github.io/taskmaster-pro/",
    repo: "https://github.com/Derimarg/taskmaster-pro",
  },

  {
    id: "10",
    name: "weather-dashboard",
    filter: "app",
    description: "JavaScript/API/Bootstrap",
    link: "https://derimarg.github.io/weather-dashboard/",
    repo: "https://github.com/Derimarg/weather-dashboard",
  },
  {
    id: "11",
    name: "tech-blog",
    filter: "card",
    description: "Node/MySQL/Sequalize",
    link: "https://dg-tech-blog.herokuapp.com/",
    repo: "https://github.com/Derimarg/tech-blog",
  },
  {
    id: "12",
    name: "password-generator",
    filter: "app",
    description: "HTML/CSS/JavaScript",
    link: "https://derimarg.github.io/password-generator/",
    repo: "https://github.com/Derimarg/password-generator",
  },
];

export default data;
